version: "3"

networks:
  microservices_network:
    driver: bridge

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway:/usr/src/api-gateway
    networks:
      - microservices_network
    depends_on:
      - user-service
      - product-service

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    volumes:
      - ./user-service:/usr/src/user-service
    networks:
      - microservices_network

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    volumes:
      - ./product-service:/usr/src/product-service
    networks:
      - microservices_network
